### ISSUE TITLE
Needs dependency updates

### ISSUE THREAD

**Issue by Steve973** [clearlydecoded/rest-messenger#53]
Since the last update to this library was in 2018, this is in dire need of updates if I am going to continue to use it.  It should be updated to Spring Boot 2.5.5, and the thymeleaf template will need to be updated because of using variables in "onclick".  My project is your single user, but since this library is maintained by one individual, and since the last update was around 3 years ago, I am considering dropping it and moving on.  Do you intend on updating it?  I checked it out and updated it, and it takes about 5 minutes to do.  With more recent versions of spring boot, it sometimes does not pick up message/processor pairs, which is pretty odd.

Please let me know.  I will be making the decision this week.

**Comment by ychaikin** [comment]
@Steve973 You mean with the updates you made in the PR "it sometimes does not pick up message/processor pairs"?

**Comment by Steve973** [comment]
No, I have no idea if the updates in the PR help with that, or not.  On my
project, we have updated to much more recent versions of spring boot, and I
noticed it today when adding another action.  The new action is not picked
up, but it follows exactly the same pattern/implementation as the other
actions, so i can only attribute it to using two different versions of
spring boot that have diverged too much.

**Comment by ychaikin** [comment]
@Steve973 In that case, I am hesitant to proceed with your PR since you are saying there is a problem with the newest version. 

Simply updating the versions without testing everything actually works doesn't make sense to me since it does look like others have used this framework elsewhere (Not sure how you know your project is the sole user of this framework, given the number of people who have forked and and starred it, but whatever).

For your project, feel free to do as you wish.

**Comment by Steve973** [comment]
Haha, ok. One user turns to zero tomorrow.  There are too many other things that do what this aims to do, and do it better, so it's for the best.  Unfortunately, I can't get those ten minutes back that I spent in this.

**Comment by Steve973** [comment]
This whole project can be done better and much more concisely with the camel rest dsl.  You can even have as much type safety as your library provides. Not that it matters, really, but it seemed to be important to you.

The problem with your library is that it uses spring boot dependencies, so, in order to be useful, it will have to be upgraded in lock step with spring boot.  And you didn't package it in such a way that isolates the library's spring boot dependencies from a project that uses it.  So, when mismatched versions occur between this library and a project that uses it, if there are breaking changes within spring boot, your library no longer works.

This comment won't make a difference, because your hubris won't allow it, but camel simplifies what you are trying to do, even though you claim otherwise. I wouldn't argue with you about web development. Likewise, you don't have the EIP experience to challenge me legitimately.  You think you do, but it doesn't matter.  It's why this library failed.  Three people might have forked it, but they aren't using a three year old version of spring boot.

This project is defunct. RIP.
